#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_root_requirements() {
  _check_cmd \
    "activity-focused" \
    "android-activity-utils"
  _check_cmd \
    "android-display-dim" \
    "android-display-dim"
  _check_cmd \
    "lockscreen-unlock" \
    "android-lockscreen-utils"
  _check_cmd \
    "sudo" \
    "tsu"
}

# shellcheck disable=SC2034
_global_variables() {
  launch_date=""
  target_app=""
  target_activity=""
  launch_mode=""
  focus_length=""
  focus_poll=""
  display_dim=""
  touch_disabled=""
  color=""
  quiet=""
}

_focus_check() {
  local \
    _current_activity \
    _target_activity \
    _msg=()
  _current_activity="$( \
    activity-focused)"
  _target_activity="${_app}/${_app}.${_activity}"
  if [[ "${_current_activity}" != "${_target_activity}" ]]; then
    _msg=(
      "Current activity: ${_current_activity}."
    )
    _msg_info \
      "${_msg[*]}"
    _msg=(
      "Target activity: ${_target_activity}."
    )
    _msg_info \
      "${_msg[*]}"
    _activity_launch_cmd \
      "${_target_activity}"
  fi
} 

_display_dim_check() {
  android-display-dim
}

_focus_check_in() {
  _previous_activity="$( \
    activity-focused)"
}

_touch_disabled_check_in() {
  local \
    _touch_status \
    _msg=()
  if [[ "${_touch_disabled}" == "y" ]]; then
    _touch_status="$( \
      touchctl \
        status || \
        true)"
    if [[ "${_touch_status}" == "enabled" ]]; then
      _msg=(
        "Disabling touch input."
      )
      _msg_info \
        "${_msg[*]}"
      touchctl \
        "${_touchctl_opts[@]}" \
        disable || \
      true
    fi || \
      true
  fi || \
    true
}

_display_dim_check_in(){
  local \
    _msg=()
  if [[ "${_dim}" == "y" ]]; then
    _msg=(
     "De-dimming screen."
    )
    _msg_info \
      "${_msg[*]}"
    _previous_brightness="$( \
      bbrightnessctl \
        "${_bbrightnessctl_opts[@]}" \
        -m \
          root \
        get || \
        true)"
    android-display-dim
  fi
}

_display_dim_check_out() {
  local \
    _msg=()
  if [[ "${_dim}" == "y" ]]; then
    _msg=(
     "De-dimming screen."
    )
    _msg_info \
      "${_msg[*]}"
    bbrightnessctl \
      -m \
        root \
      set \
        "${_previous_brightness}" || \
      true
  fi
}

_touch_disabled_check_out() {
  local \
    _msg=()
    _touch_status
  if \
    [[ "${_touch_disabled}" == "y" ]]; then
    _touch_status="$( \
      touchctl \
        status)"
    if \
      [[ "${_touch_status}" == "disabled" ]]; then
      _msg=(
        "Re-enabling touch input."
      )
      _msg_info \
        "${_msg[*]}"
      touchctl \
        "${_touchctl_opts[@]}" \
        enable || \
      true
    fi || \
      true
  fi || \
    true
}

_focus_check_out() {
  local \
    _msg=()
  _msg=(
    "Previous activity '${_previous_activity}'."
  )
  _msg_info \
    "${_msg[*]}"
   _activity_launch_cmd \
    "${_previous_activity}"
}

_service() {
  local \
    _length="${1}" \
    _poll="${2}" \
    _dim="${3}" \
    _touch_disabled="${4}" \
    _time=0 \
    _previous_brightness \
    _previous_activity
  if [[ "quiet" == "n" ]]; then
    _bbrightnessctl_opts+=(
      -v
    )
    _touchctl_opts+=(
      -v
    )
    _viewer_app_opts+=(
      -v
    )
  fi
  lockscreen-unlock
  _touch_disabled_check_in
  _display_dim_check_in
  _focus_check_in
  while \
    (( "${_time}" < "${_length}" )); do
    _focus_check
    if [[ "${_dim}" == "y" ]]; then
      _display_dim_check
    fi
    sleep \
      "${_poll}"
    _time="$(( \
      _time + _poll ))"
  done
  _focus_check_out
  _touch_disabled_check_out
  _display_dim_check_out
}

_activity_launch_cmd() {
  local \
    _activity="${1}" \
    _cmd=() \
    _msg=()
  _msg=(
    "Launching ${_activity}."
  )
  _msg_info \
    "${_msg[*]}"
  sudo \
    am \
      start \
        -a \
          "android.intent.action.MAIN" \
        -n \
          "${_activity}" || \
   true
  su \
    -c \
    "am start -a android.intent.action.MAIN -n ${_activity}" || \
  true

}

_activity_launch() {
  local \
    _app="${1}" \
    _activity="${2}" \
    _mode="${3}" \
    _length="${4}" \
    _poll="${5}" \
    _dim="${6}" \
    _touch_disabled="${7}"
  if (( 0 < "${_length}" )); then
    _service \
      "${_length}" \
      "${_poll}" \
      "${_dim}" \
      "${_touch_disabled}"
  else
    lockscreen-unlock
    if [[ "${_dim}" == "y" ]]; then
      android-display-dim
    fi || \
      true
    _activity_launch_cmd \
      "${_app}/.${_activity}"
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "launch" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "launch" \
    "mode" \
    "root"
  _set_override \
    "focus" \
    "length" \
    "0"
  _set_override \
    "focus" \
    "poll" \
    "30"
  _set_override \
    "display" \
    "dim" \
    "n"
  _set_override \
    "touch" \
    "disabled" \
    "n"
  if [[ "${display_dim}" == "y" ]]; then
    _check_cmd \
      "bbrightnessctl"
    _check_cmd \
      "android-display-dim"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "              Launch date:   ${launch_date}"
  _msg_info "              Launch mode:   ${launch_mode}"
  _msg_info "                      App:   ${target_app}"
  _msg_info "                 Activity:   ${target_activity}"
  _msg_info "             Focus length:   ${focus_length}"
  _msg_info "               Focus poll:   ${focus_poll}"
  _msg_info "              Display dim:   ${display_dim}"
  _msg_info "           Touch disabled:   ${touch_disabled}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Launches Android activities.

Usage:
  ${app_name}
    [options]
    <app>
    <activity>
  options:
     -m <mode>            How to switch activity
                          Default: ${launch_mode}
     -L <length>          For how much time keep focus
                          Default: ${focus_length}
     -p <poll>            Time interval between focus checks
                          Default: ${focus_poll}
     -d                   Dim the display.
                          Default: ${display_dim}
     -t                   Disable the touchscreen.
                          Default: ${touch_disabled}

     -h                   This message.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:L:p:dtcvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_launch_mode="${OPTARG}" ;;
    L)
      override_focus_length="${OPTARG}" ;;
    p)
      override_focus_poll="${OPTARG}" ;;
    d)
      override_display_dim="y" ;;
    t)
      override_touch_disabled="y" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
if (( $# <= 1 )); then
  _usage \
    1
fi
target_app="${1}"
target_activity="${2}"
_set_overrides
app_opts=(
  "${target_app}"
  "${target_activity}"
  "${launch_mode}"
  "${focus_length}"
  "${focus_poll}"
  "${display_dim}"
  "${touch_disabled}"
)
_show_config
_activity_launch \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
