#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0

#    -----------------------------------------------------
#    Copyright © 2024, 2025, 2026  Pellegrino Prevete
#
#    All rights reserved
#    -----------------------------------------------------
#
#    This program is free software: you can redistribute
#    it and/or modify it under the terms of the
#    GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of
#    the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it
#    will be useful, but WITHOUT ANY WARRANTY;
#    without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#    See the GNU Affero General Public License for
#    more details.
#
#    You should have received a copy of the
#    GNU Affero General Public License
#    along with this program.
#    If not, see <https://www.gnu.org/licenses/>.

_bin="$(
  dirname \
    "$(command \
         -v \
         "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "awk" \
    "gawk"
  _check_cmd \
    "sdk-version" \
    "android-utils"
  _check_cmd \
    "sed"
  _check_cmd \
    "su"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  output_format=""
  get_mode=""
  strict_mode=""
  silent_mode=""
  color=""
  quiet=""
}

_root_get() {
  local \
    _output_format="${1}" \
    _strict_mode="${2}" \
    _silent_mode="${3}" \
    _dumpsys \
    _cmd \
    _msg=() \
    _sdk
  _sdk="$(
    sdk-version)"
  _msg=(
    "Detected SDK version '${_sdk}'."
  )
  _msg_info \
    "${_msg[*]}"
  if (( 32 < "${_sdk}" )); then
    _cmd=(
      "/system/bin/dumpsys"
        "activity"
        "activities"
    )
  elif (( "${_sdk}" < 28 )); then
    _cmd=(
      "/system/bin/dumpsys"
        "activity"
        "activities"
    )
  else
    _cmd=(
      "/system/bin/dumpsys"
        "activity"
        "activities"
    )
  fi
  _msg=(
    "Running '${_cmd[*]}'."
  )
  _msg_info \
    "${_msg[*]}"
  _dumpsys="$(
    "${_cmd[@]}" || \
    true)"
  _dumpsys_lines="$(
    echo \
      "${_dumpsys}" |
      wc \
        -l)"
  if (( "${_dumpsys_lines}" == 1 )); then
    if [[ "${_dumpsys}" == "${_permissions_error_start[*]}"* && \
          "${_dumpsys}" == *"${_permissions_error_end[*]}" ]]; then
      _pid_word="${_dumpsys#${_permissions_error_start[*]}}"
      _pid="${_pid_word%, uid=* ${_permissions_error_end[*]}}"
      _uid="${_pid_word#${_pid}, uid=*}"
      _msg=(
        "User with uid '${_uid}'"
        "has no permission to run"
        "'dumpsys'. Consider running"
        "'sudo"
            "pm"
              "grant"
                "com.termux"
                "android.permission.PACKAGE_USAGE_STATS'"
        "to enable the termux terminal application user"
        "to run some 'dumpsys activity activities'"
        "without root permission."
      )
      _msg_info \
        "${_msg[*]}"
      _dumpsys="$(
        su \
          -c \
          "${_cmd[*]}" || \
          true)"
    fi
  fi
  if [[ "${_dumpsys}" == "" ]]; then
    _msg=(
      "Error running '${_cmd[*]}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  else
    _msg=(
      "Obtained dumpsys."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  "_dumpsys_${_output_format}_encode" \
    "${_dumpsys}"
}

_dumpsys_plain_encode() {
  local \
    _dumpsys="${1}"
  echo \
    "${_dumpsys}"
}

_activity_history_json_get() {
  local \
    _hist_jq_arg \
    _activity_history_encode_opts=()
  _hist_jq_arg="[$(
    IFS=","; \
    echo \
      "${_hist[*]}")]"
  _activity_history_encode_opts+=(
    --argjson
      "history"
        "${_hist_jq_arg}"
  )
  _activity_history_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_activity_history_encode_opts[@]}" \
      '$ARGS.named.history')"
}

_sub_activity_history_json_get() {
  local \
    _sub_hist_jq_arg \
    _sub_activity_history_encode_opts=()
  _sub_hist_jq_arg="[$(
    IFS=","; \
    echo \
      "${_sub_hist[*]}")]"
  _sub_activity_history_encode_opts+=(
    --argjson
      "history"
        "${_sub_hist_jq_arg}"
  )
  _sub_activity_history_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_sub_activity_history_encode_opts[@]}" \
      '$ARGS.named.history')"
}

_activity_json_get() {
  local \
    _msg=() \
    _activity_encode_opts=() \
    _activity_history_json \
    _sub_activity_jq_arg
  _activity_json=""
  _activity_history_json=""
  _activity_encode_opts+=(
    --arg
      "task-id"
        "${_task_id}"
  )
  if [[ "${_task_object_id}" != "" ]]; then
    _activity_encode_opts+=(
      --arg
        "object-id"
          "${_task_object_id}"
    )
    _msg=(
      "Task object ID: '${_task_object_id}'."
    )
    _msg_info \
      "${_msg[*]}"
  else
    _msg=(
      "This field should always be present."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  if [[ "${_task_type}" != "" ]]; then
    _activity_encode_opts+=(
      --arg
        "task-type"
          "${_task_type}"
    )
  fi
  if (( 0 < "${#_hist[@]}" )); then
    _msg=(
      "Detected activity history"
      "structure, parsing."
    )
    _msg_info \
      "${_msg[*]}"
    _activity_history_json_get
    _activity_encode_opts+=(
      --argjson
        "history"
          "${_activity_history_json}"
    )
  else
    _msg=(
      "No activity history"
      "structure detected."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  if (( 0 < "${#_sub_activities[@]}" )); then
    _msg=(
      "Detected sub-activities"
      "structure, parsing."
    )
    _msg_info \
      "${_msg[*]}"
    _sub_activity_json_get
    _sub_activity_jq_arg="$(
      IFS=","; \
      echo \
        "[${_sub_activities[*]}]")"
    _activity_encode_opts+=(
      --argjson
        "tasks"
          "${_sub_activity_jq_arg}"
    )
  else
    _msg=(
      "No sub-activities"
      "structure detected."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  _activity_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_activity_encode_opts[@]}" \
      '$ARGS.named'
  )"
  _activities+=(
    "${_activity_json}"
  )
  if [[ "${quiet}" == "n" ]]; then
    _msg=(
      "Generated activity JSON:"
    )
    _msg_info \
      "${_msg[*]}"
    echo \
      "${_activity_json}"
  fi
}

_sub_activity_json_get() {
  local \
    _msg=() \
    _sub_activity_encode_opts=() \
    _sub_activity_history_json
  _sub_activity_history_json=""
  if [[ "${_sub_task_object_id}" != "" ]]; then
    _sub_activity_encode_opts+=(
      --arg
        "object-id"
          "${_sub_task_object_id}"
    )
  fi
  if [[ "${_sub_task_id}" != "" ]]; then
    _sub_activity_encode_opts+=(
      --arg
        "task-id"
          "${_sub_task_id}"
    )
  fi
  if [[ "${_task_type}" != "" ]]; then
    _sub_activity_encode_opts+=(
      --arg
        "task-type"
          "${_sub_task_type}"
    )
  fi
  if [[ "${_sub_task_type}" != "" ]]; then
    _sub_activity_encode_opts+=(
      --arg
        "task-type"
          "${_sub_task_type}"
    )
  fi
  if (( 0 < "${#_sub_hist[@]}" )); then
    _msg=(
      "Detected sub-activity history"
      "structure, parsing."
    )
    _msg_info \
      "${_msg[*]}"
    _sub_activity_history_json_get
    _sub_activity_encode_opts+=(
      --argjson
        "history"
          "${_sub_activity_history_json}"
    )
  else
    _msg=(
      "No sub-activity history"
      "structure detected,"
      "weird."
    )
    _msg_info \
      "${_msg[*]}"
  fi
  _sub_activity_json="$(
    jq \
      "${_jq_opts[@]}" \
      "${_sub_activity_encode_opts[@]}" \
      '$ARGS.named'
  )"
  if [[ "${_sub_activity_json}" != "" ]]; then
    _sub_activities+=(
      "${_sub_activity_json}"
    )
    if [[ "${quiet}" == "n" ]]; then
      echo \
        "${_sub_activity_json}"
    fi
  fi
}

_hist_json_get() {
  local \
    _msg=() \
    _hist_encode_opts=()
  if [[ "${_hist_index}" != "" ]]; then
    _msg=(
      "Generating JSON for history item"
      "'${_hist_index}'"
      "of task '${_index}'."
    )
    _msg_info \
      "${_msg[*]}"
    # _hist_encode_opts+=(
    #   --arg
    #     "history-id"
    #       "${_hist_index}"
    # )
    if [[ "${_task_process_name}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "processName"
            "${_task_process_name}"
      )
    fi
    if [[ "${_hist_object_id}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "object-id"
            "${_hist_object_id}"
      )
    fi
    if [[ "${_task_package_name}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "packageName"
            "${_task_package_name}"
      )
    fi
    if [[ "${_task_description_label}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "taskDescription"
            "${_task_description_label}"
      )
    fi
    if [[ "${_hist_encode_opts[*]}" != "" ]]; then
      _hist_json="$(
        jq \
          "${_jq_opts[@]}" \
          "${_hist_encode_opts[@]}" \
          '$ARGS.named')"
    else
      _msg=(
        "No activity history item"
        "in queue."
      )
      _msg_info \
        "${_msg[*]}"
    fi
    if [[ "${_hist_json}" != "" ]]; then
      _hist+=(
        "${_hist_json}"
      )
      _msg=(
        "Generated task '${_index}'"
        "history item '${_hist_index}'"
        "JSON:"
      )
      _msg_info \
        "${_msg[*]}"
      if [[ "${quiet}" == "n" ]]; then
        echo \
          "${_hist_json}"
      fi
    elif [[ "${_hist_json}" == "" && \
            "${_hist_encode_opts[*]}" != "" ]]; then
      _msg=(
        "Error generating task"
        "history JSON."
      )
      _msg_error \
        "${_msg[*]}" \
        1
    fi
  else
    _msg=(
      "No history index"
      "'_hist_index' selected,"
      "skipping."
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

_sub_hist_json_get() {
  local \
    _msg=() \
    _sub_hist_encode_opts=()
  if [[ "${_sub_hist_index}" != "" ]]; then
    _msg=(
      "Generating JSON for sub-task history item"
      "'${_sub_hist_index}'"
      "of task '${_index}'."
    )
    _msg_info \
      "${_msg[*]}"
    _sub_hist_encode_opts+=(
      --arg
        "history-id"
          "${_sub_hist_index}"
    )
    if [[ "${_sub_task_process_name}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "packageName"
            "${_sub_task_process_name}"
      )
    fi
    if [[ "${_sub_task_package_name}" != "" ]]; then
      _hist_encode_opts+=(
        --arg
          "packageName"
            "${_sub_task_package_name}"
      )
    fi
    if [[ "${_sub_task_description_label}" != "" ]]; then
      _sub_hist_encode_opts+=(
        --arg
          "taskDescription"
            "${_sub_task_description_label}"
      )
    fi
    if [[ "${_sub_hist_encode_opts[*]}" != "" ]]; then
      _sub_hist_json="$(
        jq \
          "${_jq_opts[@]}" \
          "${_sub_hist_encode_opts[@]}" \
          '$ARGS.named')"
    else
      _msg=(
        "No sub-task activity history item"
        "in queue."
      )
      _msg_info \
        "${_msg[*]}"
    fi
    if [[ "${_sub_hist_json}" != "" ]]; then
      _sub_hist+=(
        "${_sub_hist_json}"
      )
      _msg=(
        "Generated task '${_index}'"
        "sub-task history item '${_sub_hist_index}'"
        "JSON:"
      )
      _msg_info \
        "${_msg[*]}"
      if [[ "${quiet}" == "n" ]]; then
        echo \
          "${_sub_hist_json}"
      fi
    elif [[ "${_sub_hist_json}" == "" && \
            "${_sub_hist_encode_opts[*]}" != "" ]]; then
      _msg=(
        "Error generating sub-task"
        "history JSON."
      )
      _msg_error \
        "${_msg[*]}" \
        1
    fi
  else
    _msg=(
      "No sub-task history index"
      "'_sub_hist_index' selected,"
      "skipping."
    )
    _msg_info \
      "${_msg[*]}"
  fi
}

_values_clean() {
  _activity_check=""
  _activity_record_opened=""
  _activity_record_unknown_id=""
  _adjust=""
  _app_op=""
  _app_op_word=""
  _app_op_visibility=""
  _app_user=""
  _app_user_id=""
  _app_user_name=""
  _area_restricted=""
  _area_unrestricted=""
  _base_layer=""
  _base_layer_word=""
  _behavior=""
  _behavior_word=""
  _client_word=""
  _client=""
  _display_id=""
  _display_id_word=""
  _draw_state=""
  _enter_animation_pending=""
  _fit_sides=""
  _fit_sides_word=""
  _fl=""
  _fl_word=""
  _fmt=""
  _if=""
  _flags=()
  _full_configuration_string=""
  _given_content_insets=""
  _given_content_insets_word=""
  _given_visible_insets=""
  _given_visible_insets_word=""
  _gr=()
  _force_seamlessly_rotate=""
  _force_hide_non_system_overlay_window=""
  _frames_display=""
  _frames_frame=""
  _frames_insets_change=""
  _frames_insets_changed=""
  _frames_last=""
  _frames_last_word=""
  _frames_parent=""
  _frames_surface=""
  _frames_surface_word=""
  _have_frame=""
  _have_frame_word=""
  _has_surface=""
  _has_surface_word=""
  _hidden_while_suspended=""
  _ignoring_something=""
  _insets_opened=""
  _insets_param=""
  _insets_params=()
  _insets_set=""
  _is_floating_layer=""
  _is_im_window=""
  _is_on_screen=""
  _is_wallpaper=""
  _is_ready_for_display=""
  _is_ready_for_display_word=""
  _is_visible=""
  _last_freeze_duration=""
  _last_hidden=""
  _last_reported_configuration_string=""
  _layout=""
  _layout_in_display_cutout_mode=""
  _layout_sequence_number=""
  _layout_sequence_number_word=""
  _legacy_policy_visibility_after_anim=""
  _or=""
  _owner_uid=""
  _owner_uid_word=""
  _package=""
  _package_word=""
  _parent_hidden=""
  _permanently_hidden=""
  _pfl=""
  _pfl_word=""
  _policy_visibility=""
  _position=""
  _position_layout=""
  _position_layout_word=""
  _prepare_sync_seq_id=""
  _private_flags=()
  _provided_insets_object_type=""
  _provided_insets_object_type_word=""
  _receive_something=""
  _sub_task_object_id=""
  _sub_task_type=""
  _token_activity_record_user=""
  _token_token=""
  _token_type=""
  _touchable_insets=""
  _touchable_insets_word=""
  _touchable_region=""
  _touchable_region_word=""
  _task_type=""
  _ty=""
  _uid=""
  _user_activity_timeout=""
  _user_unknown_id=""
  _user_word=""
  _view_obscured=""
  _view_obscured_word=""
  _view_visibility=""
  _view_visibility_word=""
  _vsysui=""
  _vsysui_word=""
  _wanim=""
  _window_grouping_token=""
  _window_removal_allowed=""
  _window_removal_allowed_word=""
  _window_token_id=""
  _window_token_id_word=""
  _window_token_type=""
  _z_order=""
}

_insets_parse() {
  local \
    _insets_params=() \
    _msg=() \
    _param \
    _left \
    _top \
    _right \
    _bottom
  _top=""
  _left=""
  _right=""
  _bottom=""
  _insets_params+=(
    "$@"
  )
  for _param in "${_insets_params[@]}"; do
    if [[ "${_param}" == "left="* ]]; then
      _left="${_param#left=}"
      _left="${_left%\}}"
    elif [[ "${_param}" == "top="* ]]; then
      _top="${_param#top=}"
      _top="${_top%\}}"
    elif [[ "${_param}" == "right="* ]]; then
      _right="${_param#right=}"
      _right="${_right%\}}"
    elif [[ "${_param}" == "bottom="* ]]; then
      _bottom="${_param#bottom=}"
      _bottom="${_bottom%\}}"
    else
      _msg=(
        "Unknown parameter '${_param}'."
      )
      _msg_error \
        "${_msg[*]}" \
        1
    fi
  done
  if [[ "${_left}" != "" ]]; then
    _insets+=(
      "${_left}"
    )
  fi
  if [[ "${_top}" != "" ]]; then
    _insets+=(
      "${_top}"
    )
  fi
  if [[ "${_right}" != "" ]]; then
    _insets+=(
      "${_right}"
    )
  fi
  if [[ "${_bottom}" != "" ]]; then
    _insets+=(
      "${_bottom}"
    )
  fi
}

# NOTE:
#   Parsing of the fields
#   using '*_word' variables
#   is hard-coded.
#   Also the program implicitly
#   assumes some properties
#   will always be found
#   on the same line,
#   still it should come up
#   if the program is run
#   with 'strict mode' on.
_dumpsys_json_encode() {
  local \
    _dumpsys="${1}" \
    _dumpsys_activity_activities=() \
    _id \
    _activities=() \
    _activities_encode_opts=() \
    _activity \
    _activity_check \
    _activity_record_opened \
    _activity_record_unknown_id \
    _activity_word \
    _adjust \
    _app_user \
    _app_user_id \
    _app_user_name \
    _app_op \
    _app_op_word \
    _app_op_visibility \
    _areas_restricted \
    _areas_unrestricted \
    _attrs_opened \
    _base_layer \
    _base_layer_word \
    _client \
    _client_word \
    _display \
    _draw_state \
    _enter_animation_pending \
    _fit_sides \
    _fit_sides_word \
    _fl \
    _fl_word \
    _flag \
    _flags=() \
    _fmt \
    _force_hide_non_system_overlay_window \
    _force_seamlessly_rotate \
    _hist=() \
    _hist_index \
    _hist_json \
    _hist_object_id \
    _line=() \
    _private_flags=() \
    _sub_activities=() \
    _sub_hist=() \
    _sub_hist_index \
    _sub_hist_json \
    _sub_task_description_label \
    _sub_task_id \
    _sub_task_icon \
    _sub_task_icon_filename \
    _sub_task_icon_resource \
    _sub_task_object_id \
    _sub_task_opened \
    _sub_task_package_name \
    _sub_task_primary_color \
    _sub_task_process_name \
    _task_process_name \
    _sub_task_type \
    _task_description_label \
    _task_id \
    _task_object_id \
    _task_opened \
    _task_package_name \
    _task_process_name \
    _task_type \
    _task_string \
    _msg=() \
    _word \
    _word_index \
    _word_index_end
  _jq_opts+=(
    -n
  )
  _is_number='^[0-9]+$'
  _msg=(
    "Encoding dumpsys output"
    "in JSON format."
  )
  _msg_info \
    "${_msg[*]}"
  mapfile \
    -d \
      $'\n' \
    _dumpsys_activity_activities < \
    <(echo \
        "${_dumpsys}")
  _msg=(
    "Dumpsys output is '${#_dumpsys_activity_activities[@]}'"
    "lines long."
  )
  _msg_info \
    "${_msg[*]}"
  _index=-1
  _sub_task_index=-1
  _hist_json=""
  _hist_object_id=""
  _sub_activity_json=""
  _sub_hist_json=""
  _sub_task_description_label=""
  _sub_task_id=""
  _sub_task_object_id=""
  _sub_task_opened=""
  _sub_task_package_name=""
  _sub_task_process_name=""
  _sub_task_type=""
  _task_description_label=""
  _task_package_name=""
  _task_process_name=""
  _window=""
  for _line_string in "${_dumpsys_activity_activities[@]}"; do
    _line_string="${_line_string%$'\n'}"
    _line=(
      ${_line_string/\*/\\*}
    )
    if [[ "${_line_string}" == "ACTIVITY MANAGER ACTIVITIES (dumpsys activity activities)" ]]; then
      true
    elif [[ "${_line_string}" == "Display #"*" (activities from top to bottom):" ]]; then
      _display="${_line[1]#\#}"
      true
    elif [[ "${_line_string}" == "  * Task{"* ]]; then
      _task_opened="true"
      _index_display="$((
        _index + 1))"
      _msg=(
        "Parsing task '${_index_display}' line."
      )
      _msg_info \
        "${_msg[*]}"
      if (( -1 < "${_index}" )); then
        _hist_json_get
        _sub_hist_json_get
        # _sub_activity_json_get
        _activity_json_get
      fi
      _hist_json=""
      _hist=()
      _hist_index=""
      _sub_activities=()
      _sub_activity_json=""
      _sub_hist=()
      _sub_hist_index=""
      _sub_task_description_label=""
      _sub_task_id=""
      _sub_task_object_id=""
      _sub_task_opened="false"
      _sub_task_package_name=""
      _sub_task_primary_color=""
      _sub_task_process_name=""
      _sub_task_type=""
      _task_description_label=""
      _task_package_name=""
      _index="$((
        _index + 1 ))"
      _sub_task_index=-1
      _task_string="${_line_string#  \* Task\{}"
      _task_string="${_task_string%\}}"
      _line=(
        ${_task_string}
      )
      _task_object_id="${_line[0]}"
      _msg=(
        "Got task object id '${_task_object_id}'."
      )
      _msg_info \
        "${_msg[*]}"
      _task_id="${_line[1]#\#}"
      for _word in "${_line[@]:2}"; do
        if [[ "${_word}" == "type="* ]]; then
          _task_type="${_word#type=}"
        else
          _msg=(
            "Unknown param '${_word}'"
            "for Task object."
          )
          if [[ "${_silent_mode}" == "y" ]]; then
            true
          elif [[ "${_strict_mode}" == "y" ]]; then
            _msg_error \
              "${_msg[*]}" \
              1
          elif [[ "${_strict_mode}" == "n" ]]; then
            _msg_warning \
              "${_msg[*]}"
          fi
        fi
      done
      _values_clean
    elif [[ "${_line_string}" == "    * Task{"* ]]; then
      _sub_task_index="$((
        _sub_task_index + 1 ))"
      _sub_task_string="${_line_string#    \* Task\{}"
      _sub_task_string="${_sub_task_string%\}}"
      _line=(
        ${_task_string}
      )
      _sub_task_opened="true"
      _msg=(
        "Parsing sub-task line for task '${_sub_task_index}'."
      )
      _msg_info \
        "${_msg[*]}"
      if [[ "${quiet}" == "n" ]]; then
        echo \
          "${_line_string}"
      fi
      _sub_task_object_id="${_line[0]}"
      _sub_task_id="${_line[1]#\#}"
      for _word in "${_line[@]:2}"; do
        if [[ "${_word}" == "type="* ]]; then
          _sub_task_type="${_word#type=}"
        else
          _msg=(
            "Unknown param '${_word}'"
            "for sub-task object."
          )
          if [[ "${_silent_mode}" == "y" ]]; then
            true
          elif [[ "${_strict_mode}" == "y" ]]; then
            _msg_error \
              "${_msg[*]}" \
              1
          elif [[ "${_strict_mode}" == "n" ]]; then
            _msg_warning \
              "${_msg[*]}"
          fi
        fi
      done
    elif [[ "${_line_string}" == "    * Hist "* ]]; then
      _msg=(
        "Parsing task history line."
      )
      _msg_info \
        "${_msg[*]}"
      _hist_opened="true"
      _hist_index_word="${_line[2]}"
      _msg_info \
        "${_line_string}"
      _hist_index_new="${_hist_index_word#$'#'}"
      _hist_index_new="${_hist_index_new%:}"
      if [[ "${_hist_index}" != "${_hist_index_new}" ]]; then
        _msg=(
          "Old index '${_hist_index}'"
          "new index '${_hist_index_new}'."
        )
        _msg_info \
          "${_msg[*]}"
        _hist_json_get \
          "${_hist_index}"
        _hist_index="${_hist_index_new}"
      fi
      _task_description_label=""
      _hist_object_id="${_line[3]}"
      _hist_object_id="${_hist_object_id#ActivityRecord\{}"
    elif [[ "${_line_string}" == "      * Hist "* ]]; then
      _msg=(
        "Parsing sub-task history line."
      )
      _msg_info \
        "${_msg[*]}"
      _sub_hist_opened="true"
      _sub_hist_index_word="${_line[2]}"
      _sub_hist_index_new="${_sub_hist_index_word#$'#'}"
      _sub_hist_index_new="${_sub_hist_index_new%:}"
      if [[ "${_sub_hist_index}" != "${_sub_hist_index_new}" ]]; then
        _msg=(
          "Old sub-task history item index '${_sub_hist_index}'."
          "New sub-task history item index '${_sub_hist_index_new}'."
        )
        _msg_info \
          "${_msg[*]}"
        # _hist_json_get \
        #   "${_hist_index}"
        _sub_hist_index="${_sub_hist_index_new}"
      fi
      _sub_task_description_label=""
      _sub_task_icon=""
      _sub_task_icon_resource=""
      _sub_task_icon_filename=""
      _sub_task_primary_color=""
    # '    * Hist'
    #   * Task{1ad9a3a #4106 type=standard A=10182:com.b44t.messenger U=0 visible=true visibleRequested=true mode=fullscreen translucent=false sz=2}
    #        packageName=com.android.gallery3d processName=com.android.gallery3d'.
    elif [[ "${_line_string}" == "      packageName="* ]]; then
      _msg=(
        "Parsing activity history item package name."
      )
      _msg_info \
        "${_msg[*]}"
      for _word in "${_line[@]}"; do
        if [[ "${_word}" == "packageName="* ]]; then
          _task_package_name="${_word#packageName=}"
          _msg=(
            "Got task package name"
            "'${_task_package_name}'."
          )
          _msg_info \
            "${_msg[*]}"
        elif [[ "${_word}" == "processName="* ]]; then
          _task_process_name="${_word#processName=}"
        else
          _msg=(
            "Unknown parameter '${_word}'"
            "for package name line."
          )
          if [[ "${_silent_mode}" == "y" ]]; then
            true
          elif [[ "${_strict_mode}" == "y" ]]; then
            _msg_error \
              "${_msg[*]}" \
              1
          elif [[ "${_strict_mode}" == "n" ]]; then
            _msg_warning \
              "${_msg[*]}"
          fi
        fi
      done
    elif [[ "${_line_string}" == "        packageName="* ]]; then
      _msg=(
        "Parsing sub-task history item package name."
      )
      _msg_info \
        "${_msg[*]}"
      for _word in "${_line[@]}"; do
        if [[ "${_word}" == "packageName="* ]]; then
          _sub_task_package_name="${_word#packageName=}"
          _msg=(
            "Got task package name"
            "'${_sub_task_package_name}'."
          )
          _msg_info \
            "${_msg[*]}"
        elif [[ "${_word}" == "processName="* ]]; then
          _sub_task_process_name="${_word#processName=}"
        else
          _msg=(
            "Unknown parameter '${_word}'"
            "for package name line."
          )
          if [[ "${_silent_mode}" == "y" ]]; then
            true
          elif [[ "${_strict_mode}" == "y" ]]; then
            _msg_error \
              "${_msg[*]}" \
              1
          elif [[ "${_strict_mode}" == "n" ]]; then
            _msg_warning \
              "${_msg[*]}"
          fi
        fi
      done
    elif [[ "${_line_string}" == "      taskDescription: "* ]]; then
      _msg=(
        "Parsing history item task description label line."
      )
      _msg_info \
        "${_msg[*]}"
      _msg_info \
        "${_line_string}"
      if [[ "${_hist_opened}" == "false" ]]; then
        _msg=(
          "How is history item field '${_hist_opened}' not opened?"
        )
        _msg_info \
          "${_msg_info[*]}"
      elif [[ "${_hist_opened}" == "true" ]]; then
        for _word in "${_line[@]:1}"; do
          if [[ "${_word}" == "label="* ]]; then
            _task_description_label="${_line_string#      taskDescription: label=\"}"
            if [[ "${_task_description_label}" == *"\"" ]]; then
              _task_description_label="${_task_description_label%\"}"
            else
              _task_description_label="${_task_description_label%\" icon=*}"
            fi
            _msg=(
              "Got task description label"
              "'${_task_description_label}'."
            )
            _msg_info \
              "${_msg[*]}"
            break
          fi
        done
        _line_string="${_line_string#      taskDescription: label=\"${_task_description_label}\" }"
        _line=(
          ${_line_string}
        )
        for _word in "${_line[@]}"; do
          # echo \
          #   "${_word}"
          if [[ "${_word}" == "icon="* ]]; then
            _task_icon="${_word#icon=}"
            _msg=(
              "Got sub-task icon"
              "'${_task_icon}'."
            )
            _msg_info \
              "${_msg[*]}"
          elif [[ "${_word}" == "iconResource="* ]]; then
            _task_icon_resource="${_word#iconResource=}"
          elif [[ "${_word}" == "iconFilename="* ]]; then
            _task_icon_filename="${_word#iconFilename=}"
          elif [[ "${_word}" == "primaryColor="* ]]; then
            _task_primary_color="${_word#primaryColor=}"
          else
            _msg=(
              "Unknown parameter '${_word}'"
              "for task history item object."
            )
            if [[ "${_silent_mode}" == "y" ]]; then
              true
            elif [[ "${_strict_mode}" == "y" ]]; then
              _msg_error \
                "${_msg[*]}" \
                1
            elif [[ "${_strict_mode}" == "n" ]]; then
              _msg_warning \
                "${_msg[*]}"
            fi
          fi
        done
      else
        _msg=(
          "The value of '_hist_opened'"
          "is '${_hist_opened}'."
        )
        _msg_info \
          "${_msg[*]}"
      fi
    elif [[ "${_line_string}" == "        taskDescription: "* ]]; then
      _msg=(
        "Parsing sub-task history item description label line."
      )
      _msg_info \
        "${_msg[*]}"
      _msg_info \
        "Line: '${_line_string}'."
      if [[ "${_sub_hist_opened}" == "false" ]]; then
        _msg=(
          "How is sub-task history item field '${_sub_hist_opened}' not opened?"
        )
        _msg_info \
          "${_msg_info[*]}"
      _description_word_index=1
      elif [[ "${_sub_hist_opened}" == "true" ]]; then
        for _word in "${_line[@]:1}"; do
          if [[ "${_word}" == "label="* ]]; then
            _sub_task_description_label="${_line_string#        taskDescription: label=\"}"
            if [[ "${_sub_task_description_label}" == *"\"" ]]; then
              _sub_task_description_label="${_sub_task_description_label%\"}"
            else
              _sub_task_description_label="${_sub_task_description_label%\" icon=*}"
            fi
            _msg=(
              "Got sub-task description label"
              "'${_sub_task_description_label}'."
            )
            _msg_info \
              "${_msg[*]}"
            break
          fi
        done
        _line_string="${_line_string#        taskDescription: label=\"${_sub_task_description_label}\" }"
        _line=(
          ${_line_string}
        )
        for _word in "${_line[@]}"; do
          # echo \
          #   "${_word}"
          if [[ "${_word}" == "icon="* ]]; then
            _sub_task_icon="${_word#icon=}"
            _msg=(
              "Got sub-task icon"
              "'${_sub_task_icon}'."
            )
            _msg_info \
              "${_msg[*]}"
          elif [[ "${_word}" == "iconResource="* ]]; then
            _sub_task_icon_resource="${_word#iconResource=}"
          elif [[ "${_word}" == "iconFilename="* ]]; then
            _sub_task_icon_filename="${_word#iconFilename=}"
          elif [[ "${_word}" == "primaryColor="* ]]; then
            _sub_task_primary_color="${_word#primaryColor=}"
          else
            _msg=(
              "Unknown parameter '${_word}'"
              "for task history item object."
            )
            if [[ "${_silent_mode}" == "y" ]]; then
              true
            elif [[ "${_strict_mode}" == "y" ]]; then
              _msg_error \
                "${_msg[*]}" \
                1
            elif [[ "${_strict_mode}" == "n" ]]; then
              _msg_warning \
                "${_msg[*]}"
            fi
          fi
        done
      else
        _msg=(
          "The value of '_sub_hist_opened'"
          "is '${_sub_hist_opened}'."
        )
        _msg_info \
          "${_msg[*]}"
      fi
    else
      _msg=(
        "Activity '${_index}',"
      )
      if [[ "${_sub_task_opened}" == "true" ]]; then
        _msg=(
          "sub-activity '${_sub_task_id}',"
        )
      fi
      if [[ "${_hist_index}" != "" ]]; then
        _msg+=(
        "task history '${_hist_index}',"
        )
      fi
      _msg+=(
        "unparsed line '${_line_string}'."
      )
      if [[ "${_silent_mode}" == "y" ]]; then
        true
      elif [[ "${_strict_mode}" == "n" ]]; then
        _msg_warning \
          "${_msg[*]}"
      elif [[ "${_strict_mode}" == "y" ]]; then
        _msg_error \
          "${_msg[*]}" \
          1
      fi
    fi
  done
  _activities_jq_arg="[$(
    IFS=","; \
    echo \
      "${_activities[*]}")]"
  _activities_encode_opts+=(
    --argjson
      "activities"
        "${_activities_jq_arg}"
  )
  _msg=(
    "Running jq with options"
    "'${_jq_opts}"
    "${_activities_encode_opts[@]}"
  )
  _msg_info \
    "${_msg[*]}"
  jq \
    "${_jq_opts[@]}" \
    "${_activities_encode_opts[@]}" \
    '$ARGS.named.activities'
}

_full_configuration_string_parse() {
  local \
    _full_configuration_string="${1}" \
    _full_configuration=() \
    _line=() \
    _win_config_flag \
    _word
  _full_configuration=(
    ${_full_configuration_string}
  )
  _win_config_flag="false"
  # at the end.
  # for _word in "${_line[@]}"; do
  #   if [[ ]]; then
  #   fi
  # done
  # true
  # TODO:
  #   this is an example string of the type it
  #   gets given in input to this function
  #   I dont need fully parsed right now so it can stay
  #   a string as far as I'm concerned.
  #   Feel free to do it yourself.
  #   mFullConfiguration={
  #     2.0
  #     222mcc8mnc
  #     [en_US,it_IT]
  #     ldltr sw480dp
  #     w1067dp
  #     h480dp
  #     72dpi
  #     lrg
  #     long
  #     land
  #     night
  #     finger
  #     -keyb/v/h
  #     -nav/h
  #     winConfig={
  #       mBounds=Rect(0, 0 - 480, 216)
  #       mAppBounds=Rect(0, 0 - 480, 216)
  #       mMaxBounds=Rect(0, 0 - 480, 216)
  #       mDisplayRotation=ROTATION_90
  #       mWindowingMode=fullscreen
  #       mDisplayWindowingMode=fullscreen
  #       mActivityType=undefined
  #       mAlwaysOnTop=undefined
  #       mRotation=ROTATION_90}
  #       as.16
  #       s.6006
  #       fontWeightAdjustment=0}
}

_activities_info() {
  local \
    _get_mode="${1}" \
    _output_format="${2}" \
    _strict_mode="${3}" \
    _silent_mode="${4}"
  "_${_get_mode}_get" \
    "${_output_format}" \
    "${_strict_mode}" \
    "${_silent_mode}"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "for X.org environment"
      "and ad-hoc support for"
      "wayland compositors"
      "need to be written"
      "but really this is text"
      "for a cross-platform"
      "window manager, not the"
      "Android one."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
  _set_override \
    "output" \
    "format" \
    "json"
  _set_override \
    "strict" \
    "mode" \
    "n"
  _set_override \
    "silent" \
    "mode" \
    "n"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                Info mode:   ${get_mode}"
  _msg_info "            Output format:   ${output_format}"
  _msg_info "              Strict mode:   ${strict_mode}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Returns informations about activities.

Usage:

  ${app_name}
    [options]

  options:

     -m <mode>      How to obtain windows information.
                    It can be 'root' for obtaining them
                    using 'dumpsys window windows'.
                    Default: ${output_format}
     -o <format>    Output format.
                    It can be 'json' or 'plain'.
                    Default: ${output_format}
     -s             Strict mode. If enabled
                    will stop if finds
                    an unknown field.
                    Default: ${strict_mode}
     -q             Silent mode. If enabled
                    won't print warnings onto
                    stderr. Printing warnings
                    is a time-consuming operation
                    so you may want to use this
                    parameter when calling
                    the program from other
                    programs.
                    Default: ${silent_mode}

     -h             This message.
     -c             Enable color output.
     -v             Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:o:sqcvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    o)
      override_output_format="${OPTARG}" ;;
    s)
      override_strict_mode="y" ;;
    q)
      override_silent_mode="y" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
  "${output_format}"
  "${strict_mode}"
  "${silent_mode}"
)
_show_config
_activities_info \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
