#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

# I don't remember why
# I had this shebang
# so let's have it just in case
# until next test
#!/data/data/com.termux/files/usr/bin/env bash

_bin="$(
  dirname \
    "$(command \
         -v \
	 "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_sourced \
  "${_crash_bash}" \
  2>"/dev/null" \
  1>"/dev/null" || \
source \
  "${_crash_bash}"

_root_requirements() {
  _check_cmd \
    "awk" \
    "gawk"
  _check_cmd \
    "grep"
  _check_cmd \
    "su"
}

# shellcheck disable=SC2034
_global_variables() {
  get_date=""
  get_mode=""
  color=""
  quiet=""
}

_root_get() {
  local \
    _sdk
  _sdk="$(
    sdk-version)"
  if (( 32 < "${_sdk}" )); then
    _cmd=(
      "/system/bin/dumpsys"
        "activity"
        "activities"
    )
  elif (( "${_sdk}" < 28 )); then
    _cmd=(
      "/system/bin/dumpsys"
        "window"
        "windows"
    )
  else
    _cmd=(
      "/system/bin/dumpsys"
        "window"
        "windows"
    )
  fi
  _activities="$(
    su \
      -c \
      "${_cmd[*]}")"
  _activity="$(
    echo \
      "${_activities}" | \
      grep \
        "mCurrentFocus" | \
        awk \
          '{print $3}' | \
          awk \
            -F \
              '}' \
            '{print $1}')"
  echo \
    "${_activity}"
}

_activity_focused() {
  local \
    _mode="${1}" \
    _cmd=() \
    _activities
  "_${_mode}_get"
}

_auto_detect_mode() {
  local \
    _os \
    _msg=()
  _os="$(
    uname \
      -o)"
  if [[ "${_os}" == "Android" ]]; then
    _root_requirements
    echo \
      "root"
  elif [[ "${_os}" == "GNU/Linux" ]]; then
    _msg=(
      "Not implemented."
      "Something with 'xdotool'"
      "needs to be written."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
}

_set_overrides() {
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  _set_override \
    "get" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "get" \
    "mode" \
    "$(_auto_detect_mode)"
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "     Got activity at date:   ${get_date}"
  _msg_info "                 Get mode:   ${get_mode}"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Get currently focused Android activity.

Usage:

  ${app_name}
    [options]

  options:

     -m <method>          Method to obtain activity name.
                          It can be 'root'.
                          Default: ${get_mode}

     -h                   This message.
     -c                   Enable color output.
     -v                   Enable verbose output

ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    'm:a:cvh?' \
    arg; do
  case \
    "${arg}" in
    m)
      override_get_mode="${OPTARG}" ;;
    a)
      override_sdk_version="${OPTARG}" ;;
    c)
      override_color="y" ;;
    v)
      override_quiet="n" ;;
    h|?)
      _set_overrides
      _usage \
        0 ;;
    *)
      _msg=(
        "Invalid argument '${arg}'."
      )
      _msg_error \
        "${_msg[*]}" \
        0
      _set_overrides
      _usage \
        1 ;;
  esac
done
shift \
  $((
    OPTIND - 1 \
  ))
_set_overrides
app_opts=(
  "${get_mode}"
)
_show_config
_activity_focused \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
